## CM4043: Molecular Modelling: Principles and Applications
## Semester 1 2019/20
## LU Yunpeng
<hr>

## Tutorial 1: Introduction to Python 3
## Objectives
### $\bullet$ Understand the basic usage of Jupyter Notebook
### $\bullet$ General features about Python 3

<hr>


## 1. Simple Math

We can use IPython console (here is Jupyter Notebook) as a calculator.

In [1]:
3 + 2 # addition of two whole numbers

5

In [2]:
2.0 + 2.5  # addition of two floating point numbers

4.5

In [3]:
2 + 2.5 # addition of a whole number and a floating point number

4.5

In [4]:
2 + 3j - (5 + 4j)   # addition of two complex numbers

(-3-1j)

In [5]:
3 + 4 * 12 - (2**3/4)

49.0

## 2. Variable Assignment

In **Python**, variable assignement is: `Variable Name = Value or Expression`. For example:

In [6]:
a = 1.28   # the value 0.2 is assigned to variable a once this line is run
a

1.28

In [7]:
a = 0.5 + 0.78 # An addition expression
a

1.28

In [8]:
b = 0.5
c = 0.78
a = b + c # An addition expression of using variables
a

1.28

Python allows you to assign a single value to several variables simultaneously. For example,

In [9]:
a = b = c = 1    # an integer object of value 1 is created and is referenced by three variables, a, b, and c
print(a)   # print variable a's value

1


In [10]:
a, b, c = 1, 2, "john"  # sometimes, this multivariate assignment is called tuple unpacking
print(a)
print(b)
print(c)

1
2
john


## 3. String

**Strings** are amongst the most popular types in Python. We can create them simply by enclosing characters in single quotes (`''`) or double quotes (`""`). Python treats single quotes the same as double quotes. Creating strings is as simple as assigning a value to a variable. For example: 

In [11]:
var1 = 'Hello World!'          #singple quotes
var2 = "Python Programming"    #double quotes

var1, var2

('Hello World!', 'Python Programming')

We can use a number (positive or negative) to index to access character(s) in a string

In [12]:
var1[1]    # Why the character to show is 'e', or 'H'?

'e'

In [13]:
var1[0]    # index starts from 0

'H'

In [14]:
var1[-1]  # counting from right hand side 

'!'

In [15]:
var1[2:5]  # substring of a string

'llo'

Two or more strings can be **added** to make a longer string. This is called String **concatenation**. For example:

In [16]:
s = var1 + var2
s

'Hello World!Python Programming'

Call function `len()` to equiry the length of a string object. (Question: what is an object in a computer programming?)

In [17]:
len(s)

30

Split a long string into several short words/substrings. For exmaple:

In [18]:
s.split()   #default delimiter, a blank space

['Hello', 'World!Python', 'Programming']

In [19]:
s.split("!")   # delimiter is set to "!"

['Hello World', 'Python Programming']

And a string object is immutable, meaning that we can not change its content. For example,

In [20]:
s[3] = 'i'  # try to change letter 'l' to 'i'

TypeError: 'str' object does not support item assignment

## 3. List

A **list** is a data structure in Python. It is a collection of objects. Each object is an element in the list, which can be indexed by a number. The implest way to create a list object is by variable assignment with all elements in a pair of square bracket `[]`. For example,

In [23]:
a = [1, 2.0, 'hello', 5 + 1.0]
a

[1, 2.0, 'hello', 6.0]

In [24]:
a[2]     # index starts from 0

'hello'

In [25]:
print(a[1])
a[1] = 'abc'   # element in a list is mutable
print(a[1])

2.0
abc


In [26]:
len(a)     # the length of list a

4

In [27]:
a.append("world")
a

[1, 'abc', 'hello', 6.0, 'world']

## 4. Tuple

A tuple is an immutable list. A tuple can not be changed in any way once it is created. The simplest way to build a tuple object is by variable assignment with elments in a pair of `()`. For example,

In [28]:
a = (1, 2.0, 'hello', 5 + 1.0)
a

(1, 2.0, 'hello', 6.0)

In [29]:
a[0] = 5    # change the first element from 1 to 5
a[0]

TypeError: 'tuple' object does not support item assignment

In [30]:
a.append("Python")

AttributeError: 'tuple' object has no attribute 'append'

## 5. Set

A set is an unordered collection of **unique** values. A single set can contain values of any immutable datatype. Once you have two sets, you can do standard set operations like union, intersection, and set difference. A set is created by variable assignment with unique elements in a pair of `{}`. For example,

In [31]:
a_set = {'a', False, 'b', True, 'mpilgrim', 42} # elements are unique and unordered.
a_set

{42, False, True, 'a', 'b', 'mpilgrim'}

In [32]:
a_set.add(14)
a_set

{14, 42, False, True, 'a', 'b', 'mpilgrim'}

In [ ]:
len(a_set)

In [33]:
a_set.discard(14)
a_set

{42, False, True, 'a', 'b', 'mpilgrim'}

## 6. Dictionary

A dictionary is an **unordered set** of **key-value** pairs. When you add a key to a dictionary, you must also add a value for that key. (You can always change the value later.) Python dictionaries are optimized for retrieving the value when you know the key, but not the other way around. The simplest way to create a dictionary object is by variable assignment of `{key:value}`. For example,

In [34]:
a_dict = {'server': 'db.diveintopython3.org', 'user': 'dora', 'database': 'blog'}
a_dict

{'server': 'db.diveintopython3.org', 'user': 'dora', 'database': 'blog'}

In [35]:
a_dict['server']

'db.diveintopython3.org'

In [36]:
a_dict['user'] = 'mark'
a_dict

{'server': 'db.diveintopython3.org', 'user': 'mark', 'database': 'blog'}

In [37]:
a_dict.keys()

dict_keys(['server', 'user', 'database'])

In [38]:
a_dict.values()

dict_values(['db.diveintopython3.org', 'mark', 'blog'])

In [39]:
a_dict.items()

dict_items([('server', 'db.diveintopython3.org'), ('user', 'mark'), ('database', 'blog')])

In [40]:
a_dict['User'] = 'John'
a_dict

{'server': 'db.diveintopython3.org',
 'user': 'mark',
 'database': 'blog',
 'User': 'John'}

## 7. Loop

A loop statement allows us to execute a statement or group of statements multiple times.

<img src="./Figures/loop_architecture.jpg" width="300" height="300" />

For example, 

In [41]:
# a while loop example
i = 1
while i < 6:
  print(i)
  i += 1

1
2
3
4
5


In [42]:
# a for loop example
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)

apple
banana
cherry


## 8. Function

A function is a block of code which only runs when it is called. You can pass data, known as parameters, into a function. A function can return data as a result.Python uses`def` keyword to define a function. For example,

In [43]:
def poly(x, a, b, c):
    y = a * x ** 2 + b * x + c
    return y

x = 1
poly(x, 1, 2, 3)

6

The Python interpreter has a number of functions built into it that are always available for certain usage.

<img src="./Figures/python-built-in-functions_1.png" width="800" height="800" />

## 9. Numpy Array

**Numpy** is the core library for scientific computing in **Python**. It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [44]:
import numpy as np

a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [45]:
a + 2

array([3, 4, 5, 6, 7])

In [46]:
a + a

array([ 2,  4,  6,  8, 10])

## 10. Python Reserved Keywords and Built-in Functions

Keywords are the reserved words in Python. We cannot use a keyword as variable name, function name or any other identifier.

Here's a list of all keywords in Python Programming,


    | False | class | finally | is | return |
    | None  | continue | for | lambda | try |
    | True | def | from | nonlocal | while |
    | and | del | global | not | with |
    | as | elif | if | or | yield |
    | assert | else | import | pass |
    | break | except | in | raise |


In [48]:
import keyword

print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


Finally, as the end of this introduction, I like to show you the "guidelines" of Python, the **Zen of Python**.

In [49]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
