## CM4044: AI In Chemistry
## Semester 1 2019/20

<hr>

## Tutorial 1c: Introduction to Numpy Part III
## Objectives
### $\bullet$ Statistics Calculations
### $\bullet$ Linear Algebra Basics

<hr>



In [2]:
import numpy as np

## 1. Statistics Calculations

## 1.1 `sum()`

To calculate the sum of elements in a `ndarray` object. The sum operation depends on data type. For example,

In [4]:
a = np.arange(1,11).reshape(2,5)
print(a)
print()

b = np.sum(a)
print(b)
print()

b = np.sum(a, axis = 0)    #sum elements along axis 0, the result is 1D array of five elements
print(b)
print()

b = np.sum(a, axis = 1)    #sum elements along axis 1, the result is 1D array of two elements
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

55

[ 7  9 11 13 15]

[15 40]


The example above about the use of `numpy.sum(a)` can be change to use 'ndarray.sum()', that is, `sum()` is also a function of array object.

In [3]:
a = np.arange(1,11).reshape(2,5)
print(a)
print()

b = a.sum()
print(b)
print()

b = a.sum(axis = 0)    #sum elements along axis 0, the result is 1D array of five elements
print(b)
print()

b = a.sum(axis = 1)    #sum elements along axis 1, the result is 1D array of two elements
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

55

[ 7  9 11 13 15]

[15 40]


## 1.2 `prod()`

The calculation of product of elements in an array. The usage is similar to the `sum()` function.

In [4]:
b = a.prod()
print(b)
print()

b = a.prod(axis = 0)    #products of elements along axis 0, the result is 1D array of five elements
print(b)
print()

b = a.prod(axis = 1)    #products of elements along axis 1, the result is 1D array of two elements
print(b)

3628800

[ 6 14 24 36 50]

[  120 30240]


or

In [5]:
b = np.prod(a)
print(b)
print()

b = np.prod(a, axis = 0)    #sum elements along axis 0, the result is 1D array of five elements
print(b)
print()

b = np.prod(a, axis = 1)    #sum elements along axis 1, the result is 1D array of two elements
print(b)

3628800

[ 6 14 24 36 50]

[  120 30240]


## 1.3 `max()` and `min()`

The calculation of maximum or minimum of elements in an array. The usage is similar to the `sum()` function. See example below.

In [6]:
from numpy.random import randint
a = randint(6, size=(3, 4))   # generate random integer smaller than 6 and store them in 3 by 4 array.
print(a)
print()

b = a.max()     # global maximum
print(b)
c = a.min()     # global minimum
print(c)

print()

b = a.max(axis = 0)    #maximium elements along axis 0, the result is 1D array of five elements
print(b)
c = a.min(axis = 0)
print(c)

print()

b = a.max(axis = 1)    #maximium elements along axis 0, the result is 1D array of five elements
print(b)
c = a.min(axis = 1)
print(c)

[[2 2 5 0]
 [4 0 2 1]
 [3 4 3 1]]

5
0

[4 4 5 1]
[2 0 2 0]

[5 4 4]
[0 0 1]


## 1.4 `argmax()` and `argmin()`

These two methods return the index of maximum or minimum element in the array. The usage is similar to the above functions.

In [7]:
b = a.argmax()
print(b)

print()

b = a.argmin(axis=0)
print(b)

print()

b = a.argmax(axis=1)
print(b)

2

[0 1 1 0]

[2 0 1]


## 1.5 `mean()` and `average()`

`numpy.mean()` returns the average of the array elements. The average is taken over the flattened array by default, otherwise over the specified axis. There is also `mean()` function of `ndarray` object, and returns the same value. For example,

In [8]:
b = a.mean()
print(b)
print()

b = np.mean(a)
print(b)
print()

b = np.mean(a, axis=0)
print(b)
print()

b = a.mean(axis=0)
print(b)

2.25

2.25

[3.         2.         3.33333333 0.66666667]

[3.         2.         3.33333333 0.66666667]


`numpy.average()` computes weighted average of elements in an array. By default, every element has the same weight.This method is not a member function of `ndarray`!

In [9]:
b = np.average(a)
print(b)
print()
#a.average()   #doesn't work

b = np.average(a, axis=0)
print(b)
print()

b = np.average(a, axis=0,weights=[1,2,2]) # the shape of weights must be the same as the shape of axis 0
print(b)

2.25

[3.         2.         3.33333333 0.66666667]

[3.2 2.  3.  0.8]


## 1.6 `std()` and `var()`

`std()` computes the standard deviation of an array over specified axis. It is both a free function in `numpy` package and a member function of `ndarray` object. `var()` computes variance of an array over specified axis. Same as `std()`, it is both a free function in `numpy` package and a member function of `ndarray` object too.

In [10]:
b = a.std()   # same as b = np.std(a)
print(b)

print()

b = a.std(axis = 1)  # same as b = np.std(a, axis = 1)
print(b)
print()

b = a.var()    # same as b = np.var(a)
print(b)
print()

b = a.var(axis=1)   # same as b = np.bar(a, axis = 1)
print(b)

1.5343293866268306

[1.78535711 1.47901995 1.08972474]

2.3541666666666665

[3.1875 2.1875 1.1875]


## 1.7 `clip()`

This function limits the value of elements in an array based on the input interval. For example

In [11]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 800]])
print(a)
print()

 
# the interval is [2, 5], any value smaller repleaced by 2, any value bigger replaced 5.
b = np.clip(a, 2, 5)   # same as a.clip(2,5)
print(b)

[[  1   2   3   4]
 [  5   6   7 800]]

[[2 2 3 4]
 [5 5 5 5]]


## 2. Linear Algebra

Linear algebra is one of the most important mathematical topics to do data science. Python’s NumPy has fast efficient functions for all standard linear albegra/matrix operations. Here we will see 9 important and useful linear algebra operations using NumPy and linalg module in NumPy.

### 2.1 Dot product of two arrays


`numpy.dot(a,b)` function calculates the dot product of two arrays (a,b), which can be vector or matrix, provide the calculation is defined.

If a and b are 1D vectors, there is no need to differenciate whether they are row or column vectors, the only requirement is they have the same number of elements.

$$ a = [a_0, a_1, ...] $$ and $$ b = [b_0, b_1, ...] $$, $$ a \centerdot b = \sum_{i=0}^{n} a_0 b_0 + a_1 b_1 + ... + a_n b_n$$

If a is matrix and b is 1D row vector, the dot product is a row vector after calculations.
$$
a = 
\left[ 
\begin{array}{cccc}
a_{00} & a_{01} & a_{02} \\ 
a_{10} & a_{11} & a_{12} \\ 
\vdots & \vdots & \vdots \\
a_{n0} & a_{n1} & a_{n2} 
\end{array} 
\right]
\quad
\textrm{ and }
\quad
b = 
\left[ 
\begin{array}{cccc}
b_0 
b_1 
b_2
\end{array} 
\right]
$$

$$
ab = [ 
a_{00} b_{0} + a_{01} b_{1} + a_{02} b_{2}, a_{10} b_{0} + a_{11} b_{1} + a_{12} b_{2}, \cdots, a_{n0} b_{0} + a_{n1} b_{1} + a_{n2} b_{2} ]
$$

If a is matrix and b is 1D column vector, the dot product is a column vector after calculations.
$$
a = 
\left[ 
\begin{array}{cccc}
a_{00} & a_{01} & a_{02} \\ 
a_{10} & a_{11} & a_{12} \\ 
\vdots & \vdots & \vdots \\
a_{n0} & a_{n1} & a_{n2} 
\end{array} 
\right]
\quad
\textrm{ and }
\quad
b = 
\left[ 
\begin{array}{cccc}
b_0 \\ 
b_1 \\ 
b_2
\end{array} 
\right]
\quad
ab  =
\left[ 
\begin{array}{c}
a_{00}b_{0} + a_{01} b_{1} + a_{02} b_{2} &  \\ 
a_{10}b_{0} + a_{11} b_{1} + a_{12} b_{2} \\ 
\vdots\\
a_{n0}b_{0} + a_{n1} b_{1} + a_{n2} b_{2}
\end{array} 
\right]
$$

If both a and b are matrix, there is requirement on the dimensionalities of a and b, a's column dimension must be the same as b's row dimension.
If a is matrix and b is 1D column vector, the dot product is a column vector after calculations.
$$
a = 
\left[ 
\begin{array}{cccc}
a_{00} & a_{01} & a_{02} \\ 
a_{10} & a_{11} & a_{12} \\ 
\vdots & \vdots & \vdots \\
a_{n0} & a_{n1} & a_{n2} 
\end{array} 
\right]
\quad
\textrm{ and }
\quad
b = 
\left[ 
\begin{array}{cccc}
b_{00} & b_{01} \\ 
b_{10} & b_{11} \\ 
b_{20} & b_{21}
\end{array} 
\right]
\quad
ab  =
\left[ 
\begin{array}{cc}
a_{00}b_{00} + a_{01} b_{10} + a_{02} b_{20} & a_{00}b_{01} + a_{01} b_{11} + a_{02} b_{21}\\ 
a_{10}b_{00} + a_{11} b_{10} + a_{12} b_{20} & a_{10}b_{01} + a_{11} b_{11} + a_{12} b_{21} \\ 
\vdots & \vdots\\
a_{n0}b_{00} + a_{n1} b_{10} + a_{n2} b_{20} & a_{n0}b_{01} + a_{n1} b_{11} + a_{n2} b_{21}
\end{array} 
\right]
$$



In [12]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.dot(a,b))
print(a.dot(b))


32
32


In [13]:
a = np.array([[1,2,3], [4,5,6]])    # the shape (2,3)
b = np.array([7,8,9])             # the shape (1,3), row vector
c = b.reshape(-1,1)
print(np.dot(a,b)) # calculable
print(a.dot(b))
print(np.dot(a,c))
print(a.dot(c))

[ 50 122]
[ 50 122]
[[ 50]
 [122]]
[[ 50]
 [122]]


In [14]:
a = np.array([[1,2,3], [4,5,6]])    # the shape (2,3)
b = np.array([[7,8], [9, 10],[11,12]]) # the shape (3,2)

print(np.dot(a,b))
print(a.dot(b))

[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]


### 2.2 Transpose of an array

`numpy.transpose(a)` exchange an array's row and column index. The symbol `.T` is the short hand of this operation.

In [15]:
a = np.array([[1,2,3], [4,5,6]])    # the shape (2,3)
print(a.shape)
print(a)
b = np.transpose(a)   # the shape (3,2)
print(b.shape)
print(b)
b = a.T   #the shape (3,2)
print(b.shape)
print(b)

(2, 3)
[[1 2 3]
 [4 5 6]]
(3, 2)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)
[[1 4]
 [2 5]
 [3 6]]


In [16]:
a = np.arange(120).reshape(2,3,4,5)   # Create an array with four dimensions, the shape (2,3,4,5)
print(a.shape)

b = a.T     #b is the transpose of a, also four dimension, but the shape is (5,4,3,2)
print(b.shape)

(2, 3, 4, 5)
(5, 4, 3, 2)


### 2.3 Inner product

`numpy.inner(a,b)` calculates the inner product of two arrays. Note: `inner()` is not a memeber function of `ndarray` class.

The main difference between `numpy.inner(a,b)` and `numpy.dot(a,b)` is with the case both a and b are matrix.

Case 1: a and b are 1D arrays. if a and b are both row vector or column vector, the inner product is calculable. The result is a scalar.
$$ a = [a_0, a_1, ...] $$ and $$ b = [b_0, b_1, ...] $$, $$ (a, b) = \sum_{i=0}^{n} a_0 b_0 + a_1 b_1 + ... + a_n b_n$$

In [17]:
a = np.array([1,2,3])   #(1,3)
b = np.array([4,5,6])   #(1,3)
c = np.array([[4],
              [5],
              [6]])                 #(3,1)
print(c)

d = np.inner(a,b)      # there is no a.inner(b) because inner() is not a member function of ndarray object
print(d)

#e = np.inner(a,c)
#print(d)

[[4]
 [5]
 [6]]
32


Case 2: The inner product of a matrix and a vector.

If a is matrix and b is 1D row vector, the dot product is a row vector after calculations.
$$
a = 
\left[ 
\begin{array}{cccc}
a_{00} & a_{01} & a_{02} \\ 
a_{10} & a_{11} & a_{12} \\ 
\vdots & \vdots & \vdots \\
a_{n0} & a_{n1} & a_{n2} 
\end{array} 
\right]
\quad
\textrm{ and }
\quad
b = 
\left[ 
\begin{array}{c}
b_0 
b_1 
b_2
\end{array} 
\right]
$$

$$
(a, b) = [ 
a_{00} b_{0} + a_{01} b_{1} + a_{02} b_{2}, a_{10} b_{0} + a_{11} b_{1} + a_{12} b_{2}, \cdots, a_{n0} b_{0} + a_{n1} b_{1} + a_{n2} b_{2} ]
$$

If b is 1D column vector, the inner product is not calculable.


In [18]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])    # the shape (2,3)
b = np.array([10,11,12])             # the shape (1,3), row vector
c = b.reshape(-1,1)                  # column vector
#print(c)
print(np.inner(a,b)) # calculable

#print(np.inner(a,c)) # not calculable


[ 68 167 266]


Case 3: both a and b are matrix.

If both a and b are matrix, there is requirement on the dimensionalities of a and b, a's column dimension must be the same as b's column dimension.

$$
a = 
\left[ 
\begin{array}{cccc}
a_{00} & a_{01} & a_{02} \\ 
a_{10} & a_{11} & a_{12} \\ 
\vdots & \vdots & \vdots \\
a_{n0} & a_{n1} & a_{n2} 
\end{array} 
\right]
\quad
\textrm{ and }
\quad
b = 
\left[ 
\begin{array}{cccc}
b_{00} & b_{01} & b_{02} \\ 
b_{10} & b_{11} & b_{12} 
\end{array} 
\right]
\quad
ab  =
\left[ 
\begin{array}{cc}
a_{00}b_{00} + a_{01} b_{01} + a_{02} b_{02} & a_{00}b_{10} + a_{01} b_{11} + a_{02} b_{12}\\ 
a_{10}b_{00} + a_{11} b_{01} + a_{02} b_{02} & a_{10}b_{10} + a_{11} b_{11} + a_{12} b_{12} \\ 
\vdots & \vdots\\
a_{n0}b_{00} + a_{n1} b_{01} + a_{n2} b_{02} & a_{n0}b_{10} + a_{n1} b_{11} + a_{n2} b_{12}
\end{array} 
\right]
$$



In [19]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])    # the shape (2,3)
b = np.array([[10,11,12], [13,14,15]])             # the shape (1,3), row vector
c = np.transpose(b)                  # column vector
print(c)
print(np.inner(a,b)) # calculable

#print(np.inner(a,c)) # not calculable


[[10 13]
 [11 14]
 [12 15]]
[[ 68  86]
 [167 212]
 [266 338]]


In [20]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])    # the shape (2,3)
b = np.array([[10,11,12], [13,14,15], [16,17,18]])             # the shape (1,3), row vector

# compare the result of dot product and inner product
print(a.dot(b))
print(np.inner(a,b)) # calculable


[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[[ 68  86 104]
 [167 212 257]
 [266 338 410]]


### 2.4 Inverse of a matrix

`numpy.linalg.inv(a)` computes the inverse of a matrix a.


In [21]:
from numpy.linalg import inv

a = np.array([[1., 2.], [3., 4.]])
ainv = inv(a)

print(ainv)

print(np.dot(a,ainv))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


### 2.5 Determinant of a matrix

`numpy.linalg.det(a)` calculates the determinant of a matrix.

In [22]:
from numpy.linalg import det

a = np.array([[1., 2.], [3., 4.]])

print(det(a))



-2.0000000000000004


### 2.6 Eigenvectors and eigenvalues

`numpy.linalg.eig(a)` calculates the eigenvalues and eigenvectors.

For this equation,
$$
\hat{A}u = \lambda u
$$

$ \hat{A} $ is a square matrix, $u$ is the eigenvector of $\hat{A}$ and $\lambda$ is the eigenvalue.




In [23]:
from numpy.linalg import eig

a = np.array([[1., 2.], [3., 4.]])
eigvals, eigvecs = eig(a)

print(eigvals)

print(eigvecs)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Finally, due to the limit of capacity, it is not possible to introduce all linear algebra functions avaiable in numpy. But there is a good read from [here](https://medium.com/secure-and-private-ai-math-blogging-competition/linear-algebra-and-numpy-ab18214fd752) 